### ISSUE TITLE
Options in saving json files

### ISSUE THREAD

**Issue by pecorarista** [boarpig/issue#5]
Is there any reason to save json files using `json.dump(self.issues, f)`
instead of  `json.dump(self.issues, f, ensure_ascii=False)`?

I use Japanese and so often type non-ascii characters.
The latter makes differences among versions readable.

In addition, adding another argument `indent=n` to `json.dump()` is also helpful for me.

Could you consider adding these options?

**Comment by boarpig** [comment]
I hadn't really thought about ensure_ascii option at all even though I'm finnish and we use ä and ö. It wouldn't really make a difference with portability as I think unicode would be preferable anyway. 

I didn't use indent=n option either because I didn't think people read the pure json, I just imagined it as a storage format. It would make it easier to read though, and doesn't actually take that much more space. I'll look into those.
